#pragma once
#include "korl-interface-platform-resource.h"
KORL_EXPORT KORL_FUNCTION_korl_resource_descriptorCallback_transcode(korl_resource_shader_transcode);
korl_internal void korl_resource_shader_register(void);
korl_internal Korl_Vulkan_ShaderHandle korl_resource_shader_getHandle(Korl_Resource_Handle handleResourceShader);
