#include "KmlDynApp.h"
GAME_INITIALIZE(gameInitialize)
{
	*g_gs = {};// clear all GameState memory before initializing the template
	kgtGameStateInitialize(&g_gs->kgtGameState, memory, sizeof(GameState));
	/* the KgtAssetIndex of the flipbook is automatically generated by the 
	 * kasset program, which should be installed with KML (see README.md) */
	kgtFlipBookInit(&g_gs->kfbBlob, KgtAssetIndex::gfx_blob_fbm);
}
GAME_UPDATE_AND_DRAW(gameUpdateAndDraw)
{
	if(!kgtGameStateUpdateAndDraw(g_kgs, gameKeyboard, windowIsFocused))
		return false;
	g_krb->beginFrame(0.2f, 0, 0.2f);
	g_krb->setProjectionOrthoFixedHeight(
		windowDimensions.x, windowDimensions.y, 150, 1);
	/* these function calls are all that's required to draw a flipbook 
		animation */
	kgtFlipBookStep(&g_gs->kfbBlob, deltaSeconds);
	kgtFlipBookDraw(&g_gs->kfbBlob, krb::WHITE);
	return true;
}
GAME_RENDER_AUDIO(gameRenderAudio)
{
	kgtGameStateRenderAudio(g_kgs, audioBuffer, sampleBlocksConsumed);
}
GAME_ON_RELOAD_CODE(gameOnReloadCode)
{
	kgtGameStateOnReloadCode(memory);
	g_gs = reinterpret_cast<GameState*>(memory.permanentMemory);
}
GAME_ON_PRE_UNLOAD(gameOnPreUnload)
{
}
#include "kgtGameState.cpp"
