#include "KmlGame.h"
GAME_INITIALIZE(gameInitialize)
{
	*g_gs = {};// clear all GameState memory before initializing the template
	templateGameState_initialize(&g_gs->templateGameState, memory, 
	                             sizeof(GameState));
	/* the KAssetIndex of the flipbook is automatically generated by the kasset 
		program, which should be installed with KML (see README.md) */
	kfbInit(&g_gs->kfbBlob, g_gs->templateGameState.assetManager, g_krb, 
	        KAssetIndex::gfx_blob_fbm);
}
GAME_UPDATE_AND_DRAW(gameUpdateAndDraw)
{
	if(!templateGameState_updateAndDraw(&g_gs->templateGameState, gameKeyboard, 
	                                    windowIsFocused))
		return false;
	g_krb->beginFrame(0.2f, 0, 0.2f);
	g_krb->setProjectionOrthoFixedHeight(
		windowDimensions.x, windowDimensions.y, 150, 1);
	/* these function calls are all that's required to draw a flipbook 
		animation */
	kfbStep(&g_gs->kfbBlob, deltaSeconds);
	kfbDraw(&g_gs->kfbBlob, krb::WHITE);
	return true;
}
GAME_RENDER_AUDIO(gameRenderAudio)
{
	templateGameState_renderAudio(&g_gs->templateGameState, audioBuffer, 
	                              sampleBlocksConsumed);
}
GAME_ON_RELOAD_CODE(gameOnReloadCode)
{
	templateGameState_onReloadCode(memory);
	g_gs = reinterpret_cast<GameState*>(memory.permanentMemory);
}
GAME_ON_PRE_UNLOAD(gameOnPreUnload)
{
}
#include "TemplateGameState.cpp"